type Dataset @entity {
  id: ID! # Use dataset ID from the smart contract
  owner: String!
  cid: String!
  createdAt: BigInt!
  price: BigInt!
  updatedAt: BigInt
  ratings: [DatasetRating!] @derivedFrom(field: "dataset")
  purchases: [DatasetPurchase!] @derivedFrom(field: "dataset")
  downloads: [DatasetDownload!] @derivedFrom(field: "dataset")
}

type DatasetUpdate @entity {
  id: ID! # Combination of datasetId + blockNumber or transaction hash
  datasetId: BigInt!
  newCid: String!
  newPrice: BigInt!
  blockHeight: BigInt!
  contractAddress: String!
}

type DatasetPurchase @entity {
  id: ID!
  dataset: Dataset!
  buyer: String!
  blockHeight: BigInt!
  contractAddress: String!
}

type DatasetRating @entity {
  id: ID!
  dataset: Dataset!
  rater: String!
  stars: Int!
  blockHeight: BigInt!
  contractAddress: String!
}

type DatasetDownload @entity {
  id: ID!
  dataset: Dataset!
  user: String!
  blockHeight: BigInt!
  contractAddress: String!
}
